# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-links-controller
  template:
    metadata:
      name: controller
      labels:
        app.kubernetes.io/name: ingress-links-controller
    spec:
      serviceAccountName: controller
      containers:
        - name: controller
          image: devnev/ingress-links-controller:latest
          resources:
            requests:
              cpu: 0.01
              memory: 20Mi
            limits:
              cpu: 0.1
              memory: 30Mi
          ports:
            - name: http
              containerPort: 80
            - name: probes
              containerPort: 8081
            - name: metrics
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: probes
              path: /alive
          readinessProbe:
            httpGet:
              port: probes
              path: /ready
