# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-links-controller

resources:
  - serviceAccount.yaml
  - clusterRole.yaml
  - clusterRoleBinding.yaml
  - deployment.yaml
  - service.yaml
