# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/service-v1.json
kind: Service
apiVersion: v1
metadata:
  name: controller
spec:
  selector:
    app.kubernetes.io/name: ingress-links-controller
  ports:
    - name: http
      port: 80
