# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
