name: ci

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shfmt@v1
        if: ${{ !cancelled() }}
      - uses: reviewdog/action-shellcheck@v1
        if: ${{ !cancelled() }}
        with:
          check_all_files_with_shebangs: "true"
      - name: Install KinD
        id: install-kind
        uses: helm/kind-action@v1
        if: ${{ !cancelled() }}
        with:
          install_only: "true"
      - name: Run E2E
        if: ${{ !cancelled() && steps.install-kind.conclusion == 'success' }}
        run: |
          ./e2e.sh

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: setup
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: devnev
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: devnev/ingress-links-controller
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          sbom: true
          push: true
          provenance: mode=max
          platforms: ${{ steps.setup.outputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
